### ISSUE TITLE
PredUpdateShortChatMessage not working?

### ISSUE THREAD

**Issue by nathan0** [cjongseok/mtproto#12]
Stripped down code:

```Go
func newSubscriber(mconn *mtproto.Conn) *subscriber {
	s := new(subscriber)
	s.mconn = mconn
	return s
}

type subscriber struct {
	mconn *mtproto.Conn
}

func (s *subscriber) OnUpdate(u mtproto.Update) {
    switch u.(type) {
        case *mtproto.PredUpdateShortChatMessage:
            fmt.Println("PredUpdateShortChatMessage")
        case *mtproto.PredUpdateShortMessage:
            fmt.Println("PredUpdateShortMessage")
    }
}

func main() {
    mconn, _= manager.LoadAuthentication(phoneNumber)
    mconn.AddUpdateCallback(newSubscriber(mconn))
    for {
        time.Sleep(time.Second)
    }
}
```

`PredUpdateShortMessage` works fine, but `PredUpdateShortChatMessage` doesn't, it's called when there is a message to a group/channel, is there something i'm missing/doing wrong?

Output of `u`:
```
Updates:<
  Updates:<
    UpdateNewChannelMessage:<
      Message:<
        Message:<
          Flags:264
          Id:-
          FromId:-ToId:<
            PeerChannel:<
              ChannelId:-
            >
          >
          ReplyToMsgId:-
          Date:1527894767
          Message:"Some Message"
        >
      >
      Pts:41234
      PtsCount:1
    >
  >
  Users:<
    User:<
      Flags:107
      Id:-
      AccessHash:-
      FirstName:"Some"
      Username:"User"
      Photo:<
        UserProfilePhoto:<
          PhotoId:-
          PhotoSmall:<
            FileLocation:<
              DcId:1
              VolumeId:-
              LocalId:- Secret:-
            >
          >
          PhotoBig:<
            FileLocation:<
              DcId:1 VolumeId:-
              LocalId:-
              Secret:-
            >
          >
        >
      >
      Status:<
        UserStatusRecently:<>
      >
    >
  >
  Chats:<
    Channel:<
      Flags:24904
      Id:-
      AccessHash:-
      Title:"Group Name"
      Username:"groupusername"
      Photo:<
        ChatPhoto:<
          PhotoSmall:<
            FileLocation:<
              DcId:4
              VolumeId:-
              LocalId:-
              Secret:-
            >
          >
          PhotoBig:<
            FileLocation:<
              DcId:4
              VolumeId:-
              LocalId:-
              Secret:-
            >
          >
        >
      >
      Date:1506520301
      AdminRights:<
        Value:<
          Flags:121
        >
      >
    >
  >
  Date:1527894766
>
```

**Comment by cjongseok** [comment]
@nathan0 Thanks for the good question. You can filter the messages by 'mtproto.PredUpdates'. It has a field 'Updates' which is a slice of '*mtproto.TypeUpdate', and 'mtproto.TypeUpdate.Value' is one of 
```go
// types.tl.pb.go:8131
*TypeUpdate_UpdateNewMessage
*TypeUpdate_UpdateMessageID
*TypeUpdate_UpdateDeleteMessages
*TypeUpdate_UpdateUserTyping
*TypeUpdate_UpdateChatUserTyping
...
```
Among them, what you want would be '*mtproto.TypeUpdate_UpdateNewChannelMessage'. It contains a field 'UpdateNewChannelMessage' whose type is '*mtproto.PredUpdateNewChannelMessage'. I think by printing out incoming updates in OnUpdate function, you can have better understanding of this data structure.

Quite complicated! The reason is that Telegram mtproto has a type hierarchy. Telegram's mtproto has three kinds of types, Type, Predicate, and Method. A Type is a kind of a data structure interface which has no fields, and a Predicate implements a Type. In the above case, mtproto.PredUpdateNewChannelMessage is a Predicate of a Type mtproto.TypeUpdate. gRPC recommends to implement this kind of polymorphism with [Oneof](https://developers.google.com/protocol-buffers/docs/proto3#oneof). Using it, cjongseok/mtproto defines TypeUpdate in protobuf as below:
```protobuf
// types.tl.proto:360
message TypeUpdate {
	oneof Value {
		PredUpdateNewMessage UpdateNewMessage = 1;
		PredUpdateMessageID UpdateMessageID = 2;
		PredUpdateDeleteMessages UpdateDeleteMessages = 3;
		PredUpdateUserTyping UpdateUserTyping = 4;
		PredUpdateChatUserTyping UpdateChatUserTyping = 5;
		PredUpdateChatParticipants UpdateChatParticipants = 6;
                 ...
                PredUpdateChannelReadMessagesContents UpdateChannelReadMessagesContents = 65;
        }
}
```
The use of gRPC Oneof in Go is complex, because Go does not allow hierarchical relations among types, e.g., inheritance. I believe, however, gRPC guys did their best and it would be the best implementation of such polymorphism in Go with RPC. [This document](https://developers.google.com/protocol-buffers/docs/reference/go-generated#oneof) will help you use Oneof in Go.

**Comment by cjongseok** [comment]
re-open it, if the comment does not work.
